- hosts: jarvis
  become: true
  vars:
    quadlets:
      homeassistant:
        image: ghcr.io/home-assistant/home-assistant
        tag: stable
        scope: system
        volumes:
          - /etc/homeassistant:/config
          - /var/run/dbus/system_bus_socket:/run/dbus/system_bus_socket
          - /media/cctv:/media/cctv:Z
        cap_add:
          - NET_ADMIN
          - NET_RAW
        env:
          TZ: Europe/Paris
        network: host
        podman: --privileged
      matter_server:
        image: ghcr.io/matter-js/matterjs-server
        tag: stable
        scope: system
        user: root
        exec: |-
          --storage-path /data
          --listen-address 127.0.0.1
          --primary-interface enp1s0
        volumes:
          - /etc/matter-server:/data:Z
          - /run/dbus:/run/dbus:ro
        network: host
      mosquitto:
        image: docker.io/library/eclipse-mosquitto
        tag: "2"
        scope: system
        entrypoint: /mosquitto/config/entrypoint.sh
        env_file: /etc/mosquitto/env
        volumes:
          - /etc/mosquitto/config:/mosquitto/config:Z
          - /etc/mosquitto/data:/mosquitto/data:Z
        network: host
      caddy:
        image: docker.io/library/caddy
        tag: "2"
        scope: system
        volumes:
          - /etc/caddy:/etc/caddy:Z
          - /var/lib/caddy:/data/caddy:Z
          - /var/log/caddy:/var/log/caddy:Z
          - /srv/www:/srv/www:ro,Z
        network: host
      # restreamer:
      #   image: datarhei/restreamer
      #   tag: vaapi-latest
      #   scope: system
      #   podman: --privileged
      #   volumes:
      #     - /dev/dri:/dev/dri:Z
      #     - /etc/restreamer:/core/config:Z
      #     - /usr/local/share/restreamer:/core/data:Z
      #     - /media/cctv:/media/cctv:Z
      #   ports:
      #     - 8080:8080
      #     - 8181:8181
      #     - 1935:1935
      #     - 1936:1936
      #     - 6000:6000/udp
      # shinobi:
      #   image: registry.gitlab.com/shinobi-systems/shinobi
      #   tag: dev
      #   scope: system
      #   volumes:
      #     - /usr/local/share/shinobi/database:/var/lib/mysql:Z
      #     - /usr/local/share/shinobi/data:/home/Shinobi:Z
      #     - /dev/shm/shinobiStreams:/dev/shm/streams:Z
      #     - /etc/localtime:/etc/localtime:ro,Z
      #     - /media/cctv:/media/cctv:Z
      #   ports:
      #     - 8080:8080
        # network: host
      frigate:
        image: ghcr.io/blakeblackshear/frigate
        tag: stable
        scope: system
        shm_size: 256m
        podman: --privileged
        devices:
          - /dev/dri/renderD128
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /etc/frigate:/config:Z
          - /media/cctv:/media/frigate:Z
        tmpfs:
          - /tmp/cache:size=1000000000
        env:
          TZ: Europe/Paris
        env_file: /etc/frigate/env
        ports:
          - 8971:8971
          # - 8554:8554
          # - 8555:8555/tcp
          # - 8555:8555/udp
  tasks:
    - name: Configure hostname
      hostname:
        name: jarvis
    - include_role:
        name: firewall
        apply:
          tags: firewall
      tags: firewall
      vars:
        firewall_services:
          - ssh
          - cockpit
          - dhcpv6-client
          - dns
          - mdns # needed for Matter device discovery
          - http
        firewall_ports:
          - "{{ ports.mqtt }}/tcp"
    - include_role:
        name: wireguard
        apply:
          tags: wireguard
      tags: always
    - include_role:
        name: mosquitto
    - name: Deploy /srv/www
      synchronize:
        src: www/
        dest: /srv/www/
        recursive: true
        delete: true
        rsync_opts:
          - "--chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r"
      tags: www
    - include_role:
        name: frigate
        apply:
          tags: frigate
      tags: always
      vars:
        frigate_streams:
          - "rtsp://mottie:{FRIGATE_RTSP_PASSWORD}@dojo.cam:554/stream2"
          - "rtsp://mottie:{FRIGATE_RTSP_PASSWORD}@octogone.cam:554/stream2"
    - include_role:
        name: containers
        apply:
          tags: containers
      tags: always
    - include_role:
        name: caddy
        apply:
          tags: caddy
      tags: always
      vars:
        caddy_https: false
        caddy_prometheus: false
        caddy_command: >-
          podman run --rm --security-opt label=disable
          -v /etc/caddy:/etc/caddy caddy:{{ quadlets.caddy.tag }} caddy
        http_domain: false
        caddy_entries:
          - domain: ha.jarvis.lan
            file: homeassistant
            reverses:
              - to: localhost:{{ ports.homeassistant }}
          - domain: jarvis.lan
            file: jarvis
            root: /srv/www/jarvis.lan
    - include_role:
        name: homeassistant
        apply:
          tags: homeassistant
      tags: always
    - include_role:
        name: dnsmasq
        apply:
          tags: dnsmasq
      tags: always
      vars:
        dns_local_suffixes:
          - lan
        dns_servers:
          - 192.168.0.1 # UDR
    - include_role:
        name: hosts
        apply:
          tags: hosts
      tags: always
      vars:
        hosts_map:
          192.168.1.254: freebox.lan
          192.168.0.1: udr.lan
          192.168.0.81: ganymede.lan
          192.168.0.98: octogone.lan
          192.168.0.179: astro.lan
          192.168.0.193: jarvis.lan ha.jarvis.lan
          192.168.0.199: wacca-mythos.lan
          192.168.27.65: jarvis.lan ha.jarvis.lan
        hosts_map_to_delete:
          192.168.27.65: jarvis.vpn.lan
